name: Build and Publish OpenWRT packages

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    tags:
      - openwrt-packages-*
  workflow_dispatch: {}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          TAG="openwrt-packages-$(date +%Y%m%d-%H%M%S)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG" -o ci.skip

  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        openwrt_version_git_ref:
          - openwrt-24.10
          - openwrt-25.12
        router:
          - glinet-mt6000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build packages
        run: |
          docker build -f Dockerfile.packages --build-arg REPO_OWNER="${{ github.repository_owner }}" --build-arg OPENWRT_VERSION_GIT_REF="${{ matrix.openwrt_version_git_ref }}" --build-arg ROUTER_CONFIG="${{ matrix.router }}" -t "ghcr.io/${{ github.repository_owner }}/openwrt-packages:${{ matrix.openwrt_version_git_ref }}-${{ matrix.router }}" .

      - name: Copy packages from docker image
        run: |
          docker create --name temp-container "ghcr.io/${{ github.repository_owner }}/openwrt-packages:${{ matrix.openwrt_version_git_ref }}-${{ matrix.router }}"
          docker cp temp-container:/home/me/openwrt/bin ./bin
          docker rm temp-container

      - name: Find and upload .ipk packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-packages-${{ matrix.openwrt_version_git_ref }}-${{ matrix.router }}
          path: ./bin/**/*.ipk
          if-no-files-found: ignore

      - name: Create GitHub Release with packages
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: ./bin/**/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
